---
# This playbook installs splunk apps

- name: Loop through the config files
  tags:
    - splunk
    - splunk_conf
  ansible.builtin.include_tasks:
    file: add_splunk_conf.yml
  loop: "{{ splunk_conf }} | dict2items"
  loop_control:
    loop_var: splunk_conf_list_items
  when: splunk_conf is defined
