---

- name: "check for splunk systemd service file"
  tags:
    - splunk
    - splunk_common
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{splunk_service_name}}.service"
  register: check_splunk_systemd

- name: Set use_splunk_systemd
  tags:
    - splunk
    - splunk_common
  ansible.builtin.set_fact:
    use_splunk_systemd: true
  when: check_splunk_systemd.stat.exists
