---

- name: "check for systemctl"
  tags:
    - splunk
    - splunk_common
  ansible.builtin.stat:
    path: /bin/systemctl
  register: systemctl

- name: Set systemctl
  tags:
    - splunk
    - splunk_common
  ansible.builtin.set_fact:
    use_systemctl: true
  when: systemctl.stat.exists
