---
# Main playbook for this role

- name: Call check_splunk_install
  tags:
    - splunk
    - splunk_common
  include_tasks: "check_splunk_install.yml"

- name: Find installed splunk version
  tags:
    - splunk
    - splunk_common
  shell: 'grep -w VERSION {{ splunk_home }}/etc/splunk.version | cut -d= -f 2'
  become: yes
  become_user: "{{ splunk_user }}"
  check_mode: no
  changed_when: false
  register: version_output
  when: splunk_is_installed|default(false) == true

- name: Set splunk_installed_version variable
  tags:
    - splunk
    - splunk_common
  set_fact:
    splunk_installed_version: '{{ version_output.stdout }}'
    splunk_exists: true
  when: version_output.stdout is defined

- name: Splunk version found
  tags:
    - splunk
    - splunk_common
  debug:
    msg: 'found {{ splunk_install_app }} version {{ splunk_installed_version }}'
  when: version_output.stdout is defined

- name: Set splunkforwarder systemd service name
  tags:
    - splunk
    - splunk_software
  set_fact:
    splunk_service_name: "splunkforwarder"
  when: use_systemctl == true
        and version_output.stdout is defined
        and splunk_installed_version is version_compare('7.2.2', '>=')
        and splunk_install_app == "splunkforwarder"
