---
# This playbook sets the os hostname

- name: Set os hostname to {{ inventory_hostname }}
  tags:
    - common
    - hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: set_hostname|default(false)
