---
# This playbook install a basic user with the login keys

- name: Adding splunk aliases
  tags:
    - common
    - bashrc
  ansible.builtin.copy:
    src: home/ansible_user/bashrc.splunk
    dest: "~{{ ansible_user }}/.bashrc.splunk"
    mode: '0644'
  become: true
  become_user: "{{ ansible_user }}"

- name: Insert/update bashrc for splunk stuff
  tags:
    - common
    - bashrc
  ansible.builtin.blockinfile:
    create: yes
    path: "~{{ ansible_user }}/.bashrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "export PATH"
    content: |
      if [ -f ~/.bashrc.splunk ]; then
        . ~/.bashrc.splunk
      fi
