---
# Main playbook for this role

- ansible.builtin.import_tasks: "install_app.yml"
- ansible.builtin.import_tasks: "{{app_name}}.yml"

- name: Call save_app
  tags:
    - splunk
    - splunk_baseconfig
    - save_baseconfig
    - save_baseconfig_apps
  ansible.builtin.include_tasks: "save_app.yml"
  when: splunk_save_baseconfig_apps|default(false) == true
