---
# This playbook install the base config app

- name: Fail if homePath != coldPath (SmartStore)
  tags:
    - splunk
    - splunk_baseconfig
    - org_indexer_volume_indexes
  ansible.builtin.fail:
    msg: "homePath ({{splunk_volume_defaults.homePath|default('primary')}}) must be equal to coldPath ({{splunk_volume_defaults.coldPath|default('primary')}}) when using SmartStore"
  when:
    - splunk_volume_defaults.remotePath is defined
    - splunk_volume_defaults.homePath|default("primary") != splunk_volume_defaults.coldPath|default("primary")

- name: "({{ app_name }}) rename volume:primary"
  tags:
    - splunk
    - splunk_baseconfig
    - org_indexer_volume_indexes
  ansible.builtin.replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    regexp: '^\[volume:primary\]'
    replace: '[volume:{{splunk_indexer_volumes_local|first|default(["primary"])}}]'
  when: splunk_indexer_volumes_local|length > 0

- name: "({{ app_name }}) setting volume:primary"
  tags:
    - splunk
    - splunk_baseconfig
    - org_indexer_volume_indexes
  community.general.ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    section: volume:{{item.key}}
    option: path
    value: "{{splunk_home}}/var/lib/splunk"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  loop: "{{splunk_indexer_volumes_local | dict2items}}"
  notify: Restart splunk
  when: splunk_indexer_volumes_local|length > 0

- name: "({{ app_name }}) setting volume:primary"
  tags:
    - splunk
    - splunk_baseconfig
    - org_search_volume_indexes
  community.general.ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    section: volume:primary
    option: path
    value: "{{splunk_home}}/var/lib/splunk"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: Restart splunk
  when: splunk_indexer_volumes_local|length < 1 or splunk_volume_defaults.homePath is not defined

- name: "({{ app_name }}) remove volume:secondary"
  tags:
    - splunk
    - splunk_baseconfig
    - org_search_volume_indexes
  community.general.ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    section: volume:secondary
    state: absent
    value: "{{splunk_home}}/var/lib/splunk"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: Restart splunk
