---
# This playbook configures additional settings for volumes

- name: "setting volume variable for volume '{{ volume_name }}'"
  tags:
    - splunk
    - splunk_baseconfig
    - org_indexer_volume_indexes
  community.general.ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    section: volume:{{ volume_name }}
    option: "{{ volume_var.key }}"
    value: "{{ volume_var.value }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  loop: "{{ volume_vars }} | dict2items"
  loop_control:
    loop_var: volume_var
  notify: restart splunk
