---
# This playbook installs certs for ssl on web

- name: Check key filename to copy
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.stat:
    path: "{{ splunk_auth_dir }}/{{ item }}.key"
  vars:
    cname_tmp: "{{ cname|default() }}"
  loop:
    - "{{ cname_tmp.split(',')|list }}"
    - "{{ inventory_hostname }}"
    - "{{ ip_addr|default() }}"
  register: cert_keys
  delegate_to: localhost
  become: false
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: Check pem filename to copy
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.stat:
    path: "{{ splunk_auth_dir }}/{{ item }}.pem"
  vars:
    cname_tmp: "{{ cname|default() }}"
  loop:
    - "{{ cname_tmp.split(',')|list }}"
    - "{{ inventory_hostname }}"
    - "{{ ip_addr|default() }}"
  register: cert_pems
  delegate_to: localhost
  become: false
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: Set cert file names
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.set_fact:
    key_file: "{% for result in cert_keys.results %}{% if result.stat.exists == true %}{{ result.item }}.key{% endif %}{% endfor %}"
    pem_file: "{% for result in cert_pems.results %}{% if result.stat.exists == true %}{{ result.item }}.pem{% endif %}{% endfor %}"
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: Fail if no cacert found
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.fail:
    msg: "Cannot find a .key file for host '{{ inventory_hostname }}' in the '{{ splunk_auth_dir }}' directory!"
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true and key_file == ""

- name: Fail if no pem cert found
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.fail:
    msg: "Cannot find a .pem file for host '{{ inventory_hostname }}' in the '{{ splunk_auth_dir }}' directory!"
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true and pem_file == ""

- name: Create path for custom certs
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ splunk_home }}/{{ item }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
  loop:
    - "{{ splunk_ssl.web.config.privKeyPath|dirname }}"
    - "{{ splunk_ssl.web.config.serverCert|dirname }}"
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: Copy certs file for web ssl
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.copy:
    src: "{{ splunk_auth_dir }}/{{ item.src }}"
    dest: "{{ splunk_home }}/{{ item.dest }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: '0600'
  loop:
    - {
        src: "{{ key_file }}",
        dest: "{{ splunk_ssl.web.config.privKeyPath|dirname }}",
      }
    - {
        src: "{{ pem_file }}",
        dest: "{{ splunk_ssl.web.config.serverCert|dirname }}",
      }
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: Link certs file for web ssl
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_search_base
    - web_ssl
  ansible.builtin.file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ splunk_home }}/{{ item.dest }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
  loop:
    - { src: "{{ key_file }}", dest: "{{ splunk_ssl.web.config.privKeyPath }}" }
    - { src: "{{ pem_file }}", dest: "{{ splunk_ssl.web.config.serverCert }}" }
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true
