---
# Main playbook for this role

- name: Start role tasks
  tags:
    - splunk
    - splunk_software
  ansible.builtin.debug:
    msg: "role '{{ role_name }}' start"

- name: Create Splunk Hosts index.html
  tags:
    - splunk
    - splunk_control
  ansible.builtin.template:
    src: "config/index.html.j2"
    dest: "../config/index.html"