---
# Handlers are run in the order they are listed, not in the order that they are notified
# See: https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#Notify

- name: Wait for SHC service ready and call push bundle
  tags:
    - splunk
    - splunk_common
    - search_head
    - shcluster
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
  become: yes
  become_user: "{{ splunk_user }}"
  register: shcluster_ready
  until: "shcluster_ready.stdout.find('service_ready_flag : 1') != -1 and shcluster_ready.stdout.find('status : Down') != 0"
  retries: 15
  delay: 10
  delegate_to: "{{splunk_shc_host_list|first}}"
  notify: Push shcluster bundle

- name: Push shcluster bundle
  tags:
    - splunk
    - splunk_common
    - search_head
    - shcluster
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk apply shcluster-bundle -target https://{{splunk_shc_host_list|first}}:8089 -auth admin:{{ splunk_admin_password }} --answer-yes"
  become: yes
  become_user: "{{ splunk_user }}"
  delegate_to: "{{ splunk_shc_deployer }}"

- name: Reload deploy-server
  tags:
    - splunk
    - splunk_common
    - deployment_server
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk reload deploy-server -auth admin:{{splunk_admin_password}}"
  become: yes
  become_user: "{{ splunk_user }}"
  delegate_to: "{{splunk_deployment_server|first}}"

- name: Restart splunk
  tags:
    - splunk
    - splunk_common
    - splunk_software
  ansible.builtin.service:
    name: "{{splunk_service_name}}"
    state: restarted
  become: yes
  become_user: root
  delegate_to: "{{ inventory_hostname }}"
  when: app_path == splunk_home + '/etc/apps'
