---
# This playbook install the base config app

- name: Start search head cluster node
  tags:
    - splunk
    - search_head
    - shcluster
  ansible.builtin.debug:
    msg: "Configuring search head cluster node"

- name: Set global permissions for comment macro
  ansible.builtin.include_tasks: comment_macro.yml
  tags:
    - splunk
    - search_head
    - shcluster
    - shsettings
    - comment_macro
  when:
    - inventory_hostname == splunk_shc_host_list|first
    - splunk_installed_version is version_compare('8.1.0', '<')

- name: Check if shcluster config is initialized
  tags:
    - splunk
    - search_head
    - shcluster
  ansible.builtin.shell: "{{ splunk_home }}/bin/splunk btool server list shclustering | egrep -e '^disabled = true$'"
  become: true
  become_user: "{{ splunk_user }}"
  register: need_shcluster_init
  check_mode: false
  failed_when: "need_shcluster_init.rc > 1"
  changed_when: "need_shcluster_init.rc == 0"

- name: Initialize, restart and wait for shcluster
  when: need_shcluster_init.rc == 0
  block:
    - name: Init shcluster member
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk init shcluster-config -shcluster_label {{ splunk_shc_label }} -mgmt_uri https://{{ inventory_hostname }}:8089 -replication_port {{splunk_shc_replication_port}} -secret '{{splunk_shc_pass}}' -conf_deploy_fetch_url https://{{splunk_shc_deployer}}:8089 -auth admin:{{splunk_admin_password}}"
      become: true
      become_user: "{{ splunk_user }}"

    - name: Restart splunk for cluster init (service restart)
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.include_role:
        name: splunk_software
        tasks_from: restart_splunk

    - name: Wait for splunkd port
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.include_role:
        name: splunk_common
        tasks_from: wait_for_splunkd_port

    # If we have plenty of apps, splunkd does several restarts and needs some time
    - name: Wait for splunkd full service
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.include_role:
        name: splunk_common
        tasks_from: wait_for_splunkd_full

- name: Check shcluster status
  tags:
    - splunk
    - search_head
    - shcluster
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
  become: true
  become_user: "{{ splunk_user }}"
  register: shcluster_status
  check_mode: false
  failed_when: shcluster_status.rc != 0 and shcluster_status.rc != 22
  changed_when: shcluster_status.stdout.find('service_ready_flag') == -1

- name: Bootstrap search head cluster
  tags:
    - splunk
    - search_head
    - shcluster
    - shc_bootstrap
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk bootstrap shcluster-captain -auth admin:{{ splunk_admin_password }}"
  become: true
  become_user: "{{ splunk_user }}"
  when: inventory_hostname == splunk_shc_host_list|first and shcluster_status.changed

- name: Add node to SHC and wait for it
  when: inventory_hostname != splunk_shc_host_list|first and shcluster_status.changed
  block:
    - name: Wait for the search head cluster status to be available
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
      become: true
      become_user: "{{ splunk_user }}"
      check_mode: false
      register: shcluster_ready
      until: "shcluster_ready.stdout.find('service_ready_flag') != -1"
      retries: 15
      delay: 10
      delegate_to: "{{splunk_shc_host_list|first}}"

    - name: Add node to search head cluster
      tags:
        - splunk
        - search_head
        - shcluster
        - shc_add_member
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk add shcluster-member -current_member_uri https://{{splunk_shc_host_list|first}}:8089 -auth admin:{{ splunk_admin_password }}"
      become: true
      become_user: "{{ splunk_user }}"

    - name: Find splunk servername
      tags:
        - splunk
        - search_head
        - shcluster
        - shc_add_member
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk show servername -auth admin:{{ splunk_admin_password }}"
      become: true
      become_user: "{{ splunk_user }}"
      check_mode: false
      changed_when: false
      register: splunk_servername

    - name: Wait for the node to join the cluster
      tags:
        - splunk
        - search_head
        - shcluster
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
      become: true
      become_user: "{{ splunk_user }}"
      check_mode: false
      register: shcluster_join
      until: "shcluster_join.stdout.find('label :' + splunk_servername.stdout.split(':')[1]) != -1"
      retries: 15
      delay: 10

- name: Check for first shc bundle push
  tags:
    - splunk
    - search_head
    - shcluster
  ansible.builtin.stat:
    path: "{{ splunk_home }}/var/run/splunk/deploy/apps"
    follow: true
  become: true
  become_user: "{{ splunk_user }}"
  delegate_to: "{{ splunk_shc_deployer }}"
  register: deploy_apps_stat
  when:
    - inventory_hostname == splunk_shc_host_list|last
    - shcluster_status.changed

- name: Push shc bundle if needed
  tags:
    - splunk
    - search_head
    - shcluster
  ansible.builtin.debug:
    msg: register shc bundle push
  notify: Wait for SHC service ready and call push bundle
  changed_when: not deploy_apps_stat.stat.exists|default(false)
  when:
    - not deploy_apps_stat.stat.exists|default(false)
    - inventory_hostname == splunk_shc_host_list|last
    - shcluster_status.changed

# Add single indexers as search peers
- name: Call search_peers from role search_head
  ansible.builtin.include_tasks: search_peers.yml

- name: Call update_dserver from role monitoring_console
  tags:
    - splunk
    - search_head
    - shcluster
    - splunk_baseconfig
    - monitoring_console
    - dserver
  ansible.builtin.include_role:
    name: monitoring_console
    tasks_from: update_dserver
  vars:
    splunk_dservers: "[ '{{ inventory_hostname }}' ]"
  when: splunk_monitoring_console|default()|length > 0 and inventory_hostname not in groups.role_monitoring_console
