---
# splunk_config.yml
plugin: splunkenizer

######################################################################
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# This is not working out of the box and needs manual preparation
# of a Windows Virtual Box image. This is not documented yet.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
######################################################################

virtualbox:
#  box: "centos/7" # Default
#  box: "ubuntu/xenial64"

# Splunk default settings
splunk_defaults:
#  splunk_env_name: splk
#  splunk_version: '8.1.2'
#  splunk_admin_password: 'splunklab'
#  splunk_license_file: Splunk_Enterprise.lic
#  splunk_indexes:
#    - test1
#    - test2

# Splunk hosts with its settings
splunk_hosts:
  # Indexer and Search Head on single node
  - name: shidx
    roles:
      - indexer
      - search_head
      - deployment_server

   # Universal Forwarder
  - name: winuf
    roles:
      - universal_forwarder_windows
    virtualbox:
      box: "windows10/20181113"
      cpus: 1
      memory: 2048
