---

- name: "install disable-thp systemd service"
  tags:
    - splunk
    - splunk_software
    - splunk_disable_thp
  ansible.builtin.copy:
    src: "etc/systemd/system/disable-thp.service"
    dest: "/etc/systemd/system/disable-thp.service"
    owner: root
    group: root
    mode: '0644'
  when: use_systemctl

- name: Commit changes to systemctl
  tags:
    - splunk
    - splunk_software
    - splunk_install
  ansible.builtin.command: systemctl daemon-reload
  when: use_systemctl

- name: Enable and start disable-thp service
  tags:
    - splunk
    - splunk_software
    - splunk_disable_thp
  ansible.builtin.service:
    name: disable-thp
    state: started
    enabled: yes
  when: use_systemctl
