---

- name: Find splunk archive files
  tags:
    - splunk
    - splunk_software
  ansible.builtin.find:
    path: "{{splunk_software}}/"
    pattern: "{{splunk_install_app}}-*-?inux-{{splunk_architecture|default('amd64')}}.tgz"
    file_type: file
    recurse: no
  register: splunk_archive_files
  delegate_to: localhost
  become: no

- name: Find latest splunk version
  tags:
    - splunk
    - splunk_software
  ansible.builtin.set_fact:
    splunk_target_version: "{{splunk_archive_files.files|sort(attribute='path')|map(attribute='path')|list|last|basename|regex_replace('.*-([0-9]+\\.[0-9]+[\\.]*[0-9]*[\\.]*[0-9]*)-.*', '\\1')}}"
  when: splunk_version == 'latest' and splunk_archive_files.files|length > 0

- name: Fail if no splunk binaries are found for latest version
  tags:
    - splunk
    - splunk_software
  ansible.builtin.fail:
    msg: "Cannot find latest splunk binaries in directory {{splunk_software}}, check variables 'splunk_version' and 'splunk_architecture'"
  when: splunk_version == 'latest' and splunk_target_version is not defined

- name: Set splunk_target_version
  tags:
    - splunk
    - splunk_software
  ansible.builtin.set_fact:
    splunk_target_version: "{{ splunk_version }}"
  when: splunk_version != 'latest'

- name: Get splunk archive for given version
  tags:
    - splunk
    - splunk_software
  ansible.builtin.set_fact:
    splunk_archive: '{{splunk_archive_files.files|map(attribute="path")|list|select("match",".*-"+splunk_target_version+"-.*")|list}}'
  when: splunk_archive_files.files is defined

- name: Fail if no splunk binaries are found for given version
  tags:
    - splunk
    - splunk_software
  ansible.builtin.fail:
    msg: "Cannot find splunk binary for version '{{ splunk_target_version }}' in directory {{splunk_software}}"
  when: splunk_archive is not defined or splunk_archive|length == 0

- name: List found splunk archive
  tags:
    - splunk
    - splunk_software
  ansible.builtin.debug:
    msg: "Using Splunk archive: {{splunk_archive.0}}"
  when: splunk_archive is defined
