---

- name: Stop and disable disable-thp service
  tags:
    - splunk
    - splunk_software
    - splunk_disable_thp
  ansible.builtin.service:
    name: disable-thp
    state: stopped
    enabled: no
  when: use_systemctl

- name: Remove disable-thp.service systemd file
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  ansible.builtin.file:
    path: /etc/systemd/system/disable-thp.service
    state: absent
  when: use_systemctl

- name: Commit changes to systemctl
  tags:
    - splunk
    - splunk_software
    - splunk_install
  ansible.builtin.command: systemctl daemon-reload
  when: use_systemctl