---

- name: Restart splunk
  tags:
    - splunk
    - splunk_common
    - splunk_restart
  ansible.builtin.service:
    name: "{{splunk_service_name}}"
    state: restarted
  become: true
  become_user: root
