---

- name: Start splunk
  tags:
    - splunk
    - splunk_common
    - splunk_start
  ansible.builtin.service:
    name: "{{splunk_service_name}}"
    state: started
  become: true
  become_user: root
