---

- name: Accept license and start splunk
  tags:
    - splunk
    - splunk_software
    - splunk_install
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt"
  become: true
  become_user: "{{ splunk_user }}"

- name: Stop splunk
  tags:
    - splunk
    - splunk_software
    - splunk_install
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk stop --answer-yes --no-prompt"
  become: true
  become_user: "{{ splunk_user }}"