---

- name: Stop splunk
  tags:
    - splunk
    - splunk_common
    - splunk_stop
  ansible.builtin.service:
    name: "{{splunk_service_name}}"
    state: stopped
  become: true
  become_user: root
