---
# This playbook configures splunk user interface

- name: Check if splunk first login is turned off
  tags:
    - splunk
    - splunk_software
    - ui_config
    - first_login_off
  ansible.builtin.stat:
    path: "{{ splunk_home }}/etc/.ui_login"
  register: splunk_first_login
  when: splunk_install_app == "splunk"

- name: Disable first login page
  tags:
    - splunk
    - splunk_software
    - ui_config
    - first_login_off
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/.ui_login"
    state: touch
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  when: splunk_install_app == "splunk" and not splunk_first_login.stat.exists

- name: Set user/passwd info to login page
  tags:
    - splunk
    - splunk_software
    - ui_config
    - splunk_user_password
  ansible.builtin.set_fact:
    splunk_loginpage_user_info: "<br><br><b>User: </b>admin<br><b>Password: </b>{{splunk_admin_password}}"
  when: splunk_loginpage_print_userpw|default(true)

- name: Set splunk roles info to login page
  tags:
    - splunk
    - splunk_software
    - ui_config
    - splunk_roles_info
  ansible.builtin.set_fact:
    splunk_loginpage_role_info: "<br><b>Splunk Roles: </b>{{splunk_roles}}"
  when: splunk_loginpage_print_roles|default(true)

- name: Set hostname info to login page
  tags:
    - splunk
    - splunk_software
    - ui_config
    - splunk_roles_info
  ansible.builtin.set_fact:
    splunk_loginpage_hostname_info: "<b>Hostname: </b>{{inventory_hostname}}"
  when: splunk_loginpage_print_hostname|default(true)

- name: Add user and roles info to login page
  tags:
    - splunk
    - splunk_software
    - ui_config
    - login_page_info
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf"
    section: settings
    option: "login_content"
    value: "<big>{{splunk_loginpage_hostname_info|default()}}{{splunk_loginpage_role_info|default()}}{{splunk_loginpage_user_info|default()}}</big>"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: '0644'
  notify: Restart splunk
  when:
    - splunk_install_app == "splunk"
    - splunk_loginpage_print_userpw|default(true) or splunk_loginpage_print_roles|default(true) or splunk_loginpage_print_hostname|default(true)
