---
# This playbook install the apps required in a server

- name: Add splunk group
  tags:
    - splunk
    - splunk_software
    - splunk_group
  group:
    name: "{{ splunk_group }}"
    state: present
  when: splunk_group_create|default(true) == true

- name: Add splunk user
  tags:
    - splunk
    - splunk_software
    - splunk_user
  user:
    name: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    comment: "Splunk User"
    shell: /bin/bash
    create_home: yes
    state: present
  when: splunk_user_create|default(true) == true

- name: Adding splunk aliases
  tags:
    - splunk
    - splunk_software
  template:
    src: home/splunk/bashrc.splunk.j2
    dest: "~{{ splunk_user }}/.bashrc.splunk"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: 0644

- name: Insert/update bashrc for splunk stuff
  tags:
    - splunk
    - splunk_software
  blockinfile:
    path: "~{{ splunk_user }}/.bashrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "export PATH"
    content: |
      if [ -f ~/.bashrc.splunk ]; then
        . ~/.bashrc.splunk
      fi
