---
# This playbook deploys a full splunk site

- name: Setup common settings
  tags:
    - common
  import_playbook: setup_common.yml

- name: Create splunk control
  tags:
    - common
  import_playbook: create_linkpage.yml

- name: Install the splunk software
  tags:
    - splunk
    - splunk_software
  import_playbook: install_splunk.yml

- name: Setup splunk roles
  tags:
    - splunk
    - splunk_roles
  import_playbook: setup_splunk_roles.yml

- name: Configure splunk conf settings
  tags:
    - splunk
    - splunk_conf
  import_playbook: setup_splunk_conf.yml

- name: Setup other roles
  tags:
    - other_roles
  import_playbook: setup_other_roles.yml
