---
# This playbook installs splunk apps

- name: run splunk_app role
#  hosts: role_cluster_master,role_deployer,role_deployment_server,role_heavy_forwarder,role_indexer,role_license_master,role_monitoring_console,role_search_head,role_universal_forwarder
  hosts: role_indexer,role_search_head,role_universal_forwarder
  become: yes
  become_user: root

  tasks:

    - name: call splunk_app role
      include_role:
        name: splunk_app
