---
# remove the splunk installation

- name: Remove the complete splunk installation
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: Call uninstall from role splunk_software
      include_role:
        name: splunk_software
        tasks_from: uninstall
