---
# update the hosts entires on all hosts

- name: Add hosts to /etc/hosts (Linux)
  hosts: all,!role_universal_forwarder_windows

  tasks:
    - name: Call hosts from role common
      ansible.builtin.include_role:
        name: common
        tasks_from: hosts

- name: Add hosts to /etc/hosts (Windows)
  hosts: role_universal_forwarder_windows

  tasks:
    - name: Call restart splunk from role splunk_software
      ansible.builtin.include_role:
        name: universal_forwarder_windows
        tasks_from: hosts
