---
# add a splunk web certs if not existing

- name: Add splunk web certs
  hosts: all,!role_indexer,!role_universal_forwarder,!role_universal_forwarder_windows
  roles:
    - splunk_common
  become: true
  become_user: root

  tasks:
    - name: Install certs for web ssl
      ansible.builtin.include_role:
        name: baseconfig_app
        tasks_from: splunk_ssl_web_certs
      when: splunk_ssl.web.enable and splunk_ssl.web.own_certs
